apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-system
  namespace: flux-system
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flux-system
                port:
                  number: 8080
