apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - collector/otel-collector-contrib.yaml
  - docker-compose.yaml
  - fluent-bit-service.yaml
  - fluentbit.yaml
  - grafana-values.yaml
  - prometheus-values.yaml
  - values.yaml

bases:
  - ./collector
  - ./fluent-bit
  - ./grafana
  - ./loki
  - ./prometheus
